import { StyleSheet } from 'react-native';
import theme from '@theme/theme';

export const styles = StyleSheet.create({
  timelineContainer: {
    paddingTop: 10,
    position: 'relative',
    marginLeft: 10,
    paddingBottom: 30,
  },
  timelineLine: {
    position: 'absolute',
    top: 0,
    left: 10,
    bottom: 0,
    width: 2,
    backgroundColor: 'rgba(66, 103, 212, 0.25)',
    zIndex: 1,
  },
  activeTimelineLineContainer: {
    position: 'absolute',
    top: 0,
    left: 10,
    height: 200,
    zIndex: 2,
  },
  activeTimelineLine: {
    width: 2,
    height: '100%',
    shadowColor: '#4A6BF5',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 8,
  },
  reminderItem: {
    flexDirection: 'row',
    marginBottom: 20,
    position: 'relative',
    alignItems: 'flex-start',
  },
  timeContainer: {
    position: 'absolute',
    left: -20,
    alignItems: 'center',
    top: 10,
    flexDirection: 'column',
    justifyContent: 'center',
  },
  timeText: {
    fontSize: 13,
    color: 'rgba(255, 255, 255, 0.7)',
    textAlign: 'right',
    lineHeight: 18,
  },
  timelineCircle: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#4A6BF5',
    position: 'absolute',
    left: 7,
    top: 20,
    zIndex: 3,
    shadowColor: '#4A6BF5',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 4,
  },
  reminderContent: {
    flex: 1,
    marginLeft: 25,
  },
  reminderCard: {
    marginVertical: 10,
    borderRadius: 24,
    padding: 15,
    backgroundColor: 'rgba(35, 36, 58, 0.35)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  reminderCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  reminderTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: theme.colors.white,
  },
  toggleButton: {
    width: 30,
    height: 18,
    borderRadius: 14,
    justifyContent: 'center',
    paddingHorizontal: 0,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.25)',
  },
  toggleActive: {
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
  },
  toggleInactive: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
  },
  toggleCircle: {
    width: 16,
    height: 16,
    borderRadius: 11,
    backgroundColor: '#fff',
  },
  toggleCircleActive: {
    alignSelf: 'flex-end',
  },
  descriptionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 14,
  },
  reminderDescription: {
    fontSize: 13,
    color: 'rgba(255, 255, 255, 0.9)',
    fontStyle: 'italic',
    flex: 1,
    marginRight: 10,
    lineHeight: 18,
    marginBottom: -15,
  },
  reminderTimeText: {
    fontSize: 16,
    color: 'rgba(255, 255, 255, 0.85)',
    marginBottom: -5,
    fontWeight: '500',
    marginTop: -10,
  },
  reminderFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 7,
  },
  appContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  appIconContainer: {
    width: 25,
    height: 25,
    backgroundColor: 'rgba(255,255,255,0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  appText: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.85)',
    fontWeight: '500',
  },
  reminderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: -12,
  },
  actionButton: {
    width: 35,
    height: 35,
    borderRadius: 17.5,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: -3,
  },
  profileSection: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  setByText: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.8)',
    marginRight: 8,
  },
  profileAvatar: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
});

export default styles;
